### ISSUE TITLE
MMH logo

### ISSUE THREAD

**Issue by yaroslav4167** [dmitrvk/mymusichere.me#3]
I designed MMH logos.
## Preview
| 1 (Bordered) | 2 (Unbordered) |
|------------|-------------------|
| <img src="https://user-images.githubusercontent.com/18057310/90639810-80c5ac00-e22f-11ea-989d-30fb0c67f3e0.png" width=200px> | <img src="https://user-images.githubusercontent.com/18057310/90640086-d8641780-e22f-11ea-8dde-f99b676a04a4.png" width=200px> |
|[source.zip](https://github.com/dmitrvk/mymusichere/files/5096741/source.zip)|

**Comment by yaroslav4167** [comment]
Background filled versions.
|Bordered | Unbordered |
| - | - |
|<img src="https://user-images.githubusercontent.com/18057310/90647870-1c0f4f00-e239-11ea-985d-b5a93435419d.png" width=200px>|<img src="https://user-images.githubusercontent.com/18057310/90647874-1d407c00-e239-11ea-84f1-b1a2159c753f.png" width=200px>|

**Comment by dmitrvk** [comment]
Thank you! Can you attach SVG with the gray version, please?

**Comment by yaroslav4167** [comment]
[source-fill.zip](https://github.com/dmitrvk/mymusichere.me/files/5097617/source-fill.zip)

**Comment by dmitrvk** [comment]
Thanks!

**Comment by dmitrvk** [comment]
I created a new icon for the website based on your design. See 4ba18bf.
